### ISSUE TITLE
Missing 1.10.16 on pear web site installer

### ISSUE THREAD

**Issue by txuna** [pear/pearweb_phars#11]
I checked `pearweb_phar` github(install-pear-nozlib.phar) updated 1.10.16 version but Missing 1.10.16 version  pear at web site `https://pear.php.net/install-pear-nozlib.phar` Can you update it?

web site uploaded 1.10.15 @ashnazg 

Thank you for your support

**Comment by ashnazg** [comment]
Please clarify... I'm staring that the 1.10.16 download page at pear.php.net right now:
https://pear.php.net/package/pearweb_phars/download/1.10.16

**Comment by txuna** [comment]
@ashnazg 
> Please clarify... I'm staring that the 1.10.16 download page at pear.php.net right now: https://pear.php.net/package/pearweb_phars/download/1.10.16

Yes, but when you install PHP 8.4 if you can put the option '--with-pear', the PEAR version installed is 1.10.15.

- my scenario
```bash 
# run php 8.4 on docker
docker run -d --name php-fpm -p 9000:9000 php:8.4-fpm
# attach php 8.4 docker container
docker exec -it php-fpm /bin/sh

# install or update pear
curl -O https://pear.php.net/install-pear-nozlib.phar
php install-pear-nozlib.phar
```
![image](https://github.com/user-attachments/assets/4aa84e21-5672-4ac8-862a-52480f8c9410)

but, if clone this repository, pear version 1.10.16
```bash
git clone https://github.com/pear/pearweb_phars.git
php install-pear-nozlib.phar

pear version
```

![image](https://github.com/user-attachments/assets/89e1b024-fb67-478a-9e15-7f9e0aa7a42b)

**Comment by ashnazg** [comment]
It looks to me like your docker container system is saying it already has certain versions of the individual packages installed, and thus executing the install phar is effectively _doing nothing_ because it sees the stuff already installed.
