### ISSUE TITLE
PHP 7.2 compatibility: Upgrade to Archive_Tar 1.4.3 needed

### ISSUE THREAD

**Issue by rainerjung** [pear/pearweb_phars#2]
Archive_Tar released a new version to fix PHP 7.2 compatibility (small change).

In order to be able to use the pear installer bundled with the PHP 7.2 sources it is necessary to update install-pear-nozlib.phar to include Archive_Tar 1.4.3 instead of 1.4.2.

For consistency it would be nice to update go-pear.phar as well.

For reference see:

https://github.com/pear/Archive_Tar/pull/18
https://bugs.php.net/bug.php?id=74723
https://bugs.php.net/bug.php?id=74801

Thanks a bunch and regards,

Rainer

**Comment by tvlooy** [comment]
@cweiske @ashnazg can some of you roll out new phars for pearweb_phars? You are listed as the active lead mainainers of this package

**Comment by ashnazg** [comment]
Yep, already on my list... in office tomorrow.

**Comment by ashnazg** [comment]
Releasing fix in v1.10.7 shortly.
