### ISSUE TITLE
PEAR installation links  have incorrect phar file

### ISSUE THREAD

**Issue by adamculp** [pear/pearweb_phars#8]
The link shared for installation of PEAR (http://pear.php.net/go-pear.phar) appears not to contain the latest phar file. Instead, installation returns errors because the /PEAR/REST/13.php file doesn't exist. Yet the repo for core does contain that and more: https://github.com/pear/pear-core/tree/master/PEAR/REST

**Comment by ashnazg** [comment]
@adamculp  just did a 1.10.15 release to update the archive-tar version in the phars... see if the new version gets you working again.

**Comment by BanzaiMan** [comment]
@ashnazg It appears to work now. https://travis-ci.org/travis-ci/php-src-builder/jobs/518650420#L4173

**Comment by ashnazg** [comment]
@adamculp reopen this if you still see a problem... and thanks for reporting it.

**Comment by adamculp** [comment]
Sorry, I was too busy to check until this morning. The issue is still not resolved. If you look at the link I provided: https://github.com/pear/pear-core/tree/master/PEAR/REST you will notice there are multiple numbered files according to versions. However, in the phar those files are not in there. (only the 10.php file exists)

Perhaps you are using an official release to build the phar, yet those added files are not included in the latest release despite being called by the code?

**Comment by adamculp** [comment]
I do not see a way to reopen this issue, but it should certainly be reopened.

**Comment by ashnazg** [comment]
When I open the go-pear.phar URL (https://pear.php.net/go-pear.phar) in Chrome, I see the text contents of the whole phar.  When I search for "13.", I do see the `class PEAR_REST_13 extends PEAR_REST_10` about halfway down the page.  I also see the 10.php and 11.php files included, though the 14.php file is not.

**Comment by adamculp** [comment]
I see that also, and the install now works. My apologies. The app I was looking at the phar with must have had the old contents cached.
